language: node_js
node_js:
  - 8.9.4
sudo: required
services:
  - docker
cache:
  directories:
    - ~/.npm
    - node_modules
    - client/node_modules
    - server/node_modules
install:
  - yarn
  - cd client && yarn
  - cd ../server && yarn && prisma deploy
script:
  - cd ../client && yarn start &
  - cd ../server && yarn start &
  - cd ../ && sleep 10 && $(npm bin)/cypress run --record